#!/data/data/com.termux/files/usr/bin/bash
# Start simple protocol player service

CURRENT_DIR=`dirname "$0"`
SCRIPT_NAME=`basename "$0"`

function print_help {
    echo "Usage: $CURRENT_DIR/$SCRIPT_NAME [play|stop] [producer_ip]"
}

if [[ "$1" == "play" ]]; then
    PRODUCER_IP="$2"
    if [[ -z "${PRODUCER_IP// }" ]]; then
        echo Missing producer ip. Aborted.
        exit 1
    fi
    am startservice --user 0 -a com.kaytat.simpleprotocolplayer.action.PLAY -e ip_addr $PRODUCER_IP --ei audio_port 8100 --ei sample_rate 48000 --ez stereo true --ei buffer_ms 40 com.kaytat.simpleprotocolplayer/.MusicService
elif [[ $1 == "stop" ]]; then
    am startservice --user 0 -a com.kaytat.simpleprotocolplayer.action.STOP com.kaytat.simpleprotocolplayer/.MusicService
else
    print_help
fi
